
version: '2.1'

volumes:
   db-backups:
   mapserver-data:
   sld:
   db-data:

services:
   db:
      image: kartoza/postgis:11.0-2.5
      volumes:
         - db-data:/var/lib/postgresql
      ports:
        - "25434:5432"
      env_file:
      - db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"

   mapserver:
      image: kartoza/mapserver
      volumes:
        - mapserver-data:/web
        - sld:/sld
      ports:
        - "8182:8080"
      restart: on-failure
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:80/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3


   db-dbbackups:
     image: kartoza/pg-backup:11.0
     volumes:
     - db-backups:/backups
     env_file:
     - db-backups.env
     restart: on-failure
     depends_on:
       db:
         condition: service_healthy
